version: 2

updates:
- package-ecosystem: npm
  directory: '/'
  target-branch: 'main'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 3
  reviewers:
    - gadingnst
  assignees:
    - gadingnst
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
